# Generated by Django 2.2.7 on 2019-12-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipousuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
